### ISSUE TITLE
Config Variable in README wrong?

### ISSUE THREAD

**Issue by jsh2134** [unbit/uwsgi-datadog#1]
I just installed this but uwsgi wouldn't start.

I got the following errors

```
2015-04-14_20:24:00.56737 !!! UNABLE to load uWSGI plugin: ./datadog_plugin.so: cannot open shared object file: No such file or directory !!!
2015-04-14_20:24:00.56764 unable to find "datadog" stats_pusher
```

When changing the config variable from `stats-push` to `stats_pusher` it worked just fine.

**Comment by unbit** [comment]
It looks like your plugin file is not in the current directory, try to specify it as an absolute path.

Using stats_pusher "works" because "stats_pusher" is not a uWSGI option, so the parser assumes it is an app-related option (and so it will not fail on startup, but your metrics will not be obviously sent)

**Comment by jsh2134** [comment]
Great. It worked once I moved the file. Thanks.
